apiVersion: apps/v1
kind: Deployment
metadata:
  name: recallApi-deployment
  labels:
    app: recallApi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recallApi
  template:
    metadata:
      labels:
        app: recallApi
    spec:
      containers:
      - name: recallApi
        image: recallApi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: USE_MOCK_LLM
          value: "0"
        - name: OLLAMA_HOST
          value: "http://ollama-service:11434"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
