apiVersion: v1
kind: Service
metadata:
  name: recallApi-service
  labels:
    app: recallApi
spec:
  selector:
    app: recallApi
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: NodePort
