apiVersion: v1
kind: Service
metadata:
  name: knowledgerag-service
  labels:
    app: knowledgerag
spec:
  selector:
    app: knowledgerag
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: NodePort
